In [1]:
#Importing library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import nltk
import tensorflow as tf
import os
import string
import re

In [2]:
data = pd.read_excel('sentence_past_present_future.xlsx') #importing dataset

In [3]:
data

Sentences Categorie
0               Lisa went to the supermarket yesterday.     Past 
1                  Sam cooked a tasty dinner yesterday.     Past 
2                     My brother saw a movie yesterday.     Past 
3                     Last year, I travelled to France.     Past 
4                                  I washed the dishes.     Past 
...                                                 ...       ...
2764  He will have been complaining to the plumber a...    Future
2765  The poet will have been writing a romantic poe...    Future
2766  Will she have been eating dinner when I enter ...    Future
2767  The lyricist will have been writing a realisti...    Future
2768  She will have been surprising him on his birth...    Future

[2769 rows x 2 columns]

In [4]:
y = data['Categorie'] #target variable

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() #covert target variable to numerical value.

In [6]:
y = le.fit_transform(y)

In [7]:
y

array([1, 1, 1, ..., 0, 0, 0])

In [8]:
y[0] # Past - 1

1

In [9]:
y[1000] #present - 2

2

In [10]:
y[2768] #future - 0

0

In [11]:
# Past - 1 , Present - 2  , future - 0

In [12]:
from nltk.tokenize import word_tokenize
from tensorflow.keras.preprocessing.text import one_hot
voc_size = 10000
input = []
for x in data['Sentences']:
    val = word_tokenize(x) # convert each sentence to separate list of word , separated by comma.
    one_rpr = one_hot(str(val),n=voc_size,lower=False,split=None) # encode each list of words to numerical value
    input.append(one_rpr) # appending and making a separate list of numerical value

In [13]:
input #list of numerical values of sentences

[[7393, 8823, 8836, 3359, 6486, 6075, 5893],
 [1027, 6418, 7334, 9693, 4215, 6075, 5893],
 [1569, 8411, 4631, 7334, 6602, 6075, 5893],
 [843, 9441, 5893, 1542, 9217, 8836, 1160, 5893],
 [1542, 7553, 3359, 8116, 5893],
 [1569, 6469, 1831, 7334, 7005, 7359, 9490, 5893],
 [1027, 1175, 3473, 7957, 6636, 7359, 117, 8269, 5893],
 [1542, 1040, 1506, 8836, 6336, 3359, 9809, 2872, 5087, 8382, 5893],
 [1569, 8411, 4417, 9958, 2824, 3359, 603, 1511, 5893],
 [1441, 8017, 8836, 7570, 7352, 7359, 117, 9958, 447, 3359, 2189, 5893],
 [1569, 4068, 4814, 8836, 2153, 6242, 361, 9441, 5893],
 [1542, 6300, 1250, 7474, 1542, 498, 2927, 5893],
 [505, 6623, 6494, 7334, 5552, 2928, 7814, 498, 3473, 4609, 5893],
 [6475, 6044, 7166, 8836, 3951, 7474, 6044, 5266, 7334, 301, 5893],
 [9780, 3847, 7751, 7474, 33, 498, 1947, 8269, 5889, 5893],
 [1569, 7352, 9419, 8836, 5268, 7474, 7814, 498, 3473, 9524, 5893],
 [1569, 6086, 3294, 2818, 7474, 7814, 498, 7334, 6298, 5893],
 [8595, 1296, 8523, 3794, 1231, 9719, 6494, 73

In [14]:
max(input) # 17 words list is max. so we can set 15 max

[9849, 8817, 3900, 3767, 1112, 3359, 8541, 5893]

In [15]:
input[20]

[2392,
 9491,
 8523,
 3794,
 7334,
 1678,
 1618,
 6132,
 2060,
 8666,
 7474,
 33,
 498,
 3473,
 9524,
 5893]

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [17]:
sent_length = 15 # length of words model will look for training as input data.
embedded_docs = pad_sequences(input,padding='post',maxlen=sent_length) 
#padding is 'post' - so after 15 words, it will add 0 so data will be of same length. we can also set it for 'pre'.

In [18]:
embedded_docs

array([[7393, 8823, 8836, ...,    0,    0,    0],
       [1027, 6418, 7334, ...,    0,    0,    0],
       [1569, 8411, 4631, ...,    0,    0,    0],
       ...,
       [4272, 7814, 1231, ...,    0,    0,    0],
       [1725, 1734, 9166, ..., 5893,    0,    0],
       [3065, 9166, 1231, ...,    0,    0,    0]])

In [19]:
# every row or datapoint is of same dimension now . padding make all dimensions equal.

In [20]:
embedded_docs[20] #max sentence 

array([9491, 8523, 3794, 7334, 1678, 1618, 6132, 2060, 8666, 7474,   33,
        498, 3473, 9524, 5893])

In [21]:
len(embedded_docs[20]) #max sentence length

15

In [22]:
embedded_docs[21] #normal random sentence

array([1542, 4631, 7334, 6602, 6075, 5893,    0,    0,    0,    0,    0,
          0,    0,    0,    0])

In [23]:
len(embedded_docs[21]) #normal sentence length

15

In [24]:
dim = 10  

In [25]:
model =Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 15, 10)            100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [27]:
# model.predict(embedded_docs)

In [28]:
# embedded_docs[0]

In [29]:
# model.predict(embedded_docs[0])

In [30]:
x = model.predict(embedded_docs)

87/87 [==============================] - 0s 1ms/step


In [31]:
x.shape

(2769, 15, 10)

In [32]:
x[0]

array([[ 0.03945469,  0.0295204 , -0.00068824, -0.01864363,  0.00753427,
        -0.00196494,  0.00659349, -0.04780832, -0.00354863,  0.03927144],
       [-0.04172989,  0.04197356,  0.01607703, -0.02056726,  0.02970734,
         0.04194604,  0.03678736, -0.00246549, -0.01890696,  0.04751534],
       [ 0.01531764, -0.02300317, -0.01251365,  0.0050469 , -0.02888231,
         0.02726806,  0.04314417,  0.00512921, -0.00276575,  0.0193044 ],
       [-0.03089475, -0.03929521, -0.02638087, -0.02018723,  0.03002348,
         0.01918698,  0.01118915, -0.01756584, -0.02433653, -0.00451641],
       [ 0.0439027 , -0.03759252,  0.00174908, -0.0024312 ,  0.02857805,
        -0.02289629, -0.01442187, -0.03116976, -0.00865988,  0.03145025],
       [-0.03135918, -0.04812597,  0.01435114,  0.03650599, -0.02492769,
        -0.0159731 ,  0.00418045,  0.02918967, -0.03618472,  0.02491338],
       [-0.01451985, -0.0368172 , -0.04810179,  0.00882699,  0.03019731,
        -0.02871173,  0.02385882,  0.02925745

In [33]:
x[0].shape

(15, 10)

In [34]:
y.shape

(2769,)

In [35]:
x.ndim

3

In [36]:
rows = x.shape[0] 
cols = x.shape[1] * x.shape[2]
x = x.reshape(rows,cols) #reshape 3-dim x to 2-dim .
# x had 2769 features with each feature consist of 15 rows and 10 columns .
# rows = x.shape[0] gives 2769
# cols = x.shape[1] * x.shape[2] which gives 15 x 10 = 150

In [37]:
x.shape

(2769, 150)

In [38]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.25,random_state=56) #spliting dataset

In [39]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
knn = KNeighborsClassifier(n_neighbors=5,metric='euclidean') 

In [40]:
knn.fit(x_train,y_train)

KNeighborsClassifier(metric='euclidean')

In [41]:
knn.score(x_test,y_test)

0.7518037518037518

In [42]:
knn.score(x_train,y_train)

0.8405587668593449

In [43]:
predicted_val = knn.predict(x_test)

In [44]:
from sklearn.metrics import accuracy_score , confusion_matrix , precision_score , recall_score , f1_score , roc_auc_score
def Evaluation_metrics(actual,pred):
    accuracy_sco = accuracy_score(actual,pred)
    confusion_mat = confusion_matrix(actual,pred)
    precision_sco = precision_score(actual,pred,average='macro')
    recall_sco = recall_score(actual,pred,average='macro')
    f1_sco = f1_score(actual,pred,average='macro')
    return accuracy_sco,confusion_mat,precision_sco,recall_sco,f1_sco

In [45]:
Evaluation_metrics(y_test,predicted_val)

(0.7518037518037518,
 array([[216,  18,   8],
        [ 42, 146,  40],
        [ 25,  39, 159]], dtype=int64),
 0.7501928826937699,
 0.7486391149896633,
 0.7466287420380119)

In [46]:
# Past - 1 , Present - 2  , future - 0
# created fn where we can give sentenec and it will do all process to change into numerical sentence and it will change its shape.
# and predict and return which category it belongs
from nltk.tokenize import word_tokenize
from tensorflow.keras.preprocessing.text import one_hot
def try_other_sentences(sentence):
    voc_size_val = 10000
    input_val = [sentence] 
    out_put = []
    for x in input_val:
        val = word_tokenize(x)
        one_rpr = one_hot(str(val),n=voc_size_val,lower=False,split=None)
        out_put.append(one_rpr)
    sent_length = 15
    embedded_sentence = pad_sequences(out_put,padding='post',maxlen=sent_length) #input- sentence
    value_to_pass = model.predict(embedded_sentence) 
    rows = value_to_pass.shape[0]
    cols = value_to_pass.shape[1] * value_to_pass.shape[2]
    value_to_pass = value_to_pass.reshape(rows,cols) #coverting test sentence to same shape of 'x' . as we trained on.
    return value_to_pass
def predict_output(value):
    pred = knn.predict(value)
    if pred == [1]:
        print('Past Tense',pred)
    elif pred == [2]:
        print('Present Tense',pred)
    elif pred == [0]:
        print('Future Tense',pred)

In [47]:
# sentence_1 = 'The cat slept soundly' # past tence
# sentence_2 = 'The dog barked loudly at the mail carrier.'
# sentence_3 = 'I studied for the exam all weekend.'
# sentence_4 = 'They traveled to Europe last summer.'
# sentence_5 = 'She walked to the store yesterday.'
# sentence_6 = 'They ate dinner at a new restaurant last night.'
# sentence_7 = 'He finished his homework before dinner.'
# sentence_8 = 'The rain stopped an hour ago.'
# sentence_9 = 'We saw a great movie on Saturday.'
# sentence_10 = 'The birds sing sweetly in the trees.' #present
# sentence_11 = 'What are you looking at'
# sentence_12 = 'The sun shines brightly today.'
# sentence_13 = 'They live in a big city.'
# sentence_14 = 'I listen to music while I work.'
# sentence_15 = 'The cat sleeps on the sofa.'
# sentence_16 = 'We eat lunch at noon.'
# sentence_17 = 'He works at a software company.'
# sentence_18 = 'She reads a book every night.'
# sentence_19 = 'I will visit the museum tomorrow.' # future
# sentence_20 = 'I will travel to Goa next month.'
# sentence_21 = 'He will study abroad next year.'
# sentence_22 = 'She will start her new job next week.'
# sentence_23 = 'They are going to have a party on Saturday.'
# sentence_24 = 'The scientists will conduct experiments to find a cure.'
# sentence_25 = 'The cities will experience growth in the coming years.'
# sentence_26 = 'The families will gather for the holiday celebration.'
# sentence_27 = 'The birds will migrate to warmer climates in the fall.'
# value = try_other_sentences(sentence_3)
# pred_output = predict_output(value)

In [48]:
sentence_1 = ['The cat slept soundly',
'The dog barked loudly at the mail carrier.',
'I studied for the exam all weekend.',
'They traveled to Europe last summer.',
'She walked to the store yesterday.',
'They ate dinner at a new restaurant last night.',
'He finished his homework before dinner.',
'The rain stopped an hour ago.',
'We saw a great movie on Saturday.',
'The birds sing sweetly in the trees.',
'What are you looking at',
'The sun shines brightly today.',
'They live in a big city.',
'I listen to music while I work.',
'The cat sleeps on the sofa.',
'We eat lunch at noon.',
'He works at a software company.',
'She reads a book every night.',
'I will visit the museum tomorrow.' ,
'I will travel to Goa next month.',
'He will study abroad next year.',
'She will start her new job next week.',
'They are going to have a party on Saturday.',
'The scientists will conduct experiments to find a cure.',
'The cities will experience growth in the coming years.',
'The families will gather for the holiday celebration.',
'The birds will migrate to warmer climates in the fall.']

#Results of given sentences

In [49]:
g = 1
for i in sentence_1:
    print('sentence',g,'____________________________________________')
    value = try_other_sentences(i)
    pred_output = predict_output(value)
    g += 1

sentence 1 ____________________________________________
1/1 [==============================] - 0s 23ms/step
Present Tense [2]
sentence 2 ____________________________________________
1/1 [==============================] - 0s 22ms/step
Present Tense [2]
sentence 3 ____________________________________________
1/1 [==============================] - 0s 22ms/step
Future Tense [0]
sentence 4 ____________________________________________
1/1 [==============================] - 0s 22ms/step
Present Tense [2]
sentence 5 ____________________________________________
1/1 [==============================] - 0s 22ms/step
Present Tense [2]
sentence 6 ____________________________________________
1/1 [==============================] - 0s 21ms/step
Future Tense [0]
sentence 7 ____________________________________________
1/1 [==============================] - 0s 21ms/step
Present Tense [2]
sentence 8 ____________________________________________
1/1 [==============================] - 0s 21ms/step
Past Tense [