In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
import nltk
import tensorflow as tf
import os
import string
import re

In [2]:
data = pd.read_csv('Data.csv')

In [3]:
data

Sentences  Categorie
0               Lisa went to the supermarket yesterday.          1
1                  Sam cooked a tasty dinner yesterday.          1
2                     My brother saw a movie yesterday.          1
3                     Last year, I travelled to France.          1
4                                  I washed the dishes.          1
...                                                 ...        ...
2764  He will have been complaining to the plumber a...          3
2765  The poet will have been writing a romantic poe...          3
2766  Will she have been eating dinner when I enter ...          3
2767  The lyricist will have been writing a realisti...          3
2768  She will have been surprising him on his birth...          3

[2769 rows x 2 columns]

In [4]:
# values = []
# for i in range(len(data['Sentences'])):
#     review = re.sub('[^a-zA-Z]',' ',data['Sentences'][i])
#     review = review.lower()
#     # review = review.split(',')
#     values.append(review)
# id = [ids for ids in data['Categorie']]

In [5]:
# #tokanization
# from sklearn.feature_extraction.text import CountVectorizer
# cv = CountVectorizer()
# tokenization = cv.fit_transform(values).toarray()

In [6]:
# new_data = {
#     "Sentences": [val for val in values],
#     'id': id
# }
# df = pd.DataFrame(new_data)

In [7]:
# df

In [8]:
# def sentence_to_numeric(sentence):
#     words = sentence.split()
#     unique_words = sorted(list(set(words)))
#     vocabulary = {word: index for index, word in enumerate(unique_words)}
#     numeric_representation = [vocabulary[word] for word in words]
#     return numeric_representation

In [9]:
# from nltk.tokenize import word_tokenize

# new_data = {
#     "Sentences": [word_tokenize(x) for x in df['Sentences']],
#     'id': id
# }
# df = pd.DataFrame(new_data)

In [10]:
y = data['Categorie']

In [11]:
from nltk.tokenize import word_tokenize
from tensorflow.keras.preprocessing.text import one_hot
voc_size = 10000
input = []
for x in data['Sentences']:
    val = word_tokenize(x)
    one_rpr = one_hot(str(val),n=voc_size,lower=False,split=None)
    input.append(one_rpr)

In [12]:
input

[[3764, 2245, 3377, 5762, 2358, 9865, 5777],
 [3570, 3826, 7822, 9595, 8825, 9865, 5777],
 [773, 2842, 3759, 7822, 9528, 9865, 5777],
 [1128, 8452, 5777, 8573, 6816, 3377, 9896, 5777],
 [8573, 4108, 5762, 4386, 5777],
 [773, 2978, 8488, 7822, 3169, 8371, 4129, 5777],
 [3570, 5220, 9753, 8290, 5854, 8371, 1356, 6586, 5777],
 [8573, 1505, 404, 3377, 3315, 5762, 803, 2236, 187, 9485, 5777],
 [773, 2842, 1972, 9952, 9890, 5762, 5551, 6108, 5777],
 [5561, 1242, 3377, 7368, 6458, 8371, 1356, 9952, 1456, 5762, 3322, 5777],
 [773, 7892, 3782, 3377, 9699, 7864, 9910, 8452, 5777],
 [8573, 7764, 7874, 9408, 8573, 4891, 229, 5777],
 [2414, 3540, 8419, 7822, 1227, 3898, 1986, 4891, 9753, 3204, 5777],
 [1725, 8886, 3261, 3377, 8186, 9408, 8886, 7945, 7822, 6662, 5777],
 [4424, 9729, 2023, 9408, 2713, 4891, 3662, 6586, 5620, 5777],
 [773, 6458, 2589, 3377, 2841, 9408, 1986, 4891, 9753, 5164, 5777],
 [773, 5301, 181, 9117, 9408, 1986, 4891, 7822, 4269, 5777],
 [2488, 9977, 1479, 6357, 306, 1704, 8419,

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
sent_length = 20
embedded_docs = pad_sequences(input,padding='post',maxlen=sent_length)

In [15]:
embedded_docs

array([[3764, 2245, 3377, ...,    0,    0,    0],
       [3570, 3826, 7822, ...,    0,    0,    0],
       [ 773, 2842, 3759, ...,    0,    0,    0],
       ...,
       [5535, 1986,  306, ...,    0,    0,    0],
       [8045, 6264, 3479, ...,    0,    0,    0],
       [3611, 3479,  306, ...,    0,    0,    0]])

In [16]:
dim = 15

In [17]:
# one_rpr = one_hot(data,n=voc_size,lower=False,split=" ",analyzer=None)

In [18]:
model =Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 15)            150000    
                                                                 
Total params: 150000 (585.94 KB)
Trainable params: 150000 (585.94 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.predict(embedded_docs)

87/87 [==============================] - 0s 1ms/step


array([[[ 0.04811132,  0.02602203,  0.04321751, ...,  0.01094699,
          0.03032334,  0.04334079],
        [ 0.04601768,  0.02508478,  0.03354946, ...,  0.04513956,
          0.00794178, -0.02522977],
        [-0.00641073, -0.01896054, -0.04341303, ..., -0.01563504,
         -0.0456191 ,  0.02220922],
        ...,
        [ 0.02420012,  0.00010975,  0.04970625, ..., -0.03259577,
         -0.0138026 ,  0.02378912],
        [ 0.02420012,  0.00010975,  0.04970625, ..., -0.03259577,
         -0.0138026 ,  0.02378912],
        [ 0.02420012,  0.00010975,  0.04970625, ..., -0.03259577,
         -0.0138026 ,  0.02378912]],

       [[ 0.01969005, -0.02404319,  0.02363776, ..., -0.02158792,
         -0.00632221, -0.03046149],
        [ 0.02643985,  0.00780445,  0.02329508, ...,  0.04710045,
         -0.03427928, -0.04168294],
        [-0.02861284, -0.04505005, -0.01561598, ...,  0.04504779,
         -0.02123175, -0.01831973],
        ...,
        [ 0.02420012,  0.00010975,  0.04970625, ..., -

In [21]:
embedded_docs[0]

array([3764, 2245, 3377, 5762, 2358, 9865, 5777,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0])

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 42ms/step


array([[ 0.04811132,  0.02602203,  0.04321751,  0.01941928, -0.03443535,
        -0.00795639,  0.02122524, -0.04283155, -0.03528186,  0.0374841 ,
         0.00818274, -0.03436341,  0.01094699,  0.03032334,  0.04334079],
       [ 0.04601768,  0.02508478,  0.03354946,  0.04010436, -0.02183161,
         0.01809872, -0.02198505, -0.03093994,  0.04729065, -0.01047255,
        -0.00712536,  0.01385706,  0.04513956,  0.00794178, -0.02522977],
       [-0.00641073, -0.01896054, -0.04341303,  0.00726662, -0.00868703,
         0.0144936 ,  0.02263763,  0.00390583, -0.04667544,  0.02573982,
        -0.02171081,  0.0339807 , -0.01563504, -0.0456191 ,  0.02220922],
       [ 0.00220786, -0.03224833,  0.01439061, -0.03954094, -0.00907635,
         0.00743381,  0.02821293,  0.01552442, -0.03671213, -0.04450008,
        -0.02343552,  0.01099958,  0.00470603,  0.02903619, -0.00138706],
       [-0.01106961,  0.02922307,  0.01908412, -0.01040421,  0.03013912,
        -0.00857929, -0.02511944, -0.00083777, 

In [23]:
x = model.predict(embedded_docs)

87/87 [==============================] - 0s 1ms/step


In [24]:
x.shape

(2769, 20, 15)

In [25]:
y.shape

(2769,)

In [26]:
y = list(y)

In [27]:
# y = np.expand_dims(y,axis=1)

In [28]:
y = np.array(y)

In [29]:
y

array([1, 1, 1, ..., 3, 3, 3])

In [30]:
# sent_length = 20
# embedded_y = pad_sequences(y,padding='post',maxlen=sent_length)
# dim = 15
# model =Sequential()
# model.add(Embedding(voc_size,dim,input_length=sent_length))
# model.compile('adam','mse')
# model.summary()

In [31]:
# y = model.predict(embedded_y)

In [32]:
y.shape

(2769,)

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [35]:
x_train.shape

(2076, 20, 15)

In [36]:
y_train.shape

(2076,)

In [37]:
x_test.shape

(693, 20, 15)

In [38]:
y_test.shape

(693,)

In [39]:
# timesteps = 20
# features = 15
# batch_size = 10
# x_x = np.random.rand(batch_size, timesteps, features)
# y_y = np.random.randint(0, num_classes, size=(batch_size,))

# Convert labels to one-hot encoded vectors (for categorical_crossentropy)
# y_train_one_hot = tf.keras.utils.to_categorical(y_train, num_classes=num_classes)

In [59]:
from tensorflow.keras.layers import SimpleRNN, Dense

def create_simple_rnn_model(input_shape, num_units, num_classes):
    rnn_model = Sequential()
    rnn_model.add(SimpleRNN(units=num_units, input_shape=input_shape))
    rnn_model.add(Dense(units=num_classes, activation='softmax'))
    rnn_model.add(Dense(units=1, activation='softmax')) # or 'sigmoid' for binary
    rnn_model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy']) # or 'binary_crossentropy'
    return rnn_model

In [60]:
timesteps = 20
features = 15
num_classes = 3
num_units = 32
batch_size = 2769
input_shape = (timesteps, features)

model = create_simple_rnn_model(input_shape, num_units, num_classes)

In [61]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1536      
                                                                 
 dense_1 (Dense)             (None, 3)                 99        
                                                                 
 dense_2 (Dense)             (None, 1)                 4         
                                                                 
Total params: 1639 (6.40 KB)
Trainable params: 1639 (6.40 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [62]:
# y_train_one_hot = tf.keras.utils.to_categorical(y_train)
# y_train_one_hot.shape

# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# y_train_encode = le.fit_transform(y_train)

In [63]:
# y_train_encode

In [64]:
# y_train_one_hot[0]

In [65]:
# y_train_one_hot = np.reshape()

In [66]:
# y_train_one_hot[0].shape

In [67]:
# Train the model (replace with your actual training loop)
# model.fit(x_train, y_train, epochs=10,batch_size=batch_size)

Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 2/10
1/1 [==============================] - 0s 66ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 3/10
1/1 [==============================] - 0s 37ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 4/10
1/1 [==============================] - 0s 34ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 5/10
1/1 [==============================] - 0s 34ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 6/10
1/1 [==============================] - 0s 26ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 7/10
1/1 [==============================] - 0s 34ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 8/10
1/1 [==============================] - 0s 33ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 9/10
1/1 [==============================] - 0s 38ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 10/10
1/1 [==============================] - 0s 26ms/step - loss: 0.0000e+00 - accuracy